// In-memory overlay store. Pure domain layer.
//
// Holds the editing-side truth — overlay objects keyed by id, indexed by
// pageNo, with a Pub/Sub channel so the renderer can react to mutations.
//
//   - Overlay positions are canonical (PDF point, top-left, post-rotation).
//   - Mutations flip a `dirty` flag; persistence is the caller's job
//     (M3-1: Workspace.saveOverlays + load via openPdfFile response).
//   - Spatial queries use linear scan per page (typical pages have <100
//     overlays). Switching to rbush will be revisited via ADR if profiling
//     shows the need.
//
// No SQLite, mupdf, or DOM imports. Uses `globalThis.crypto.randomUUID`
// so the same module works in both Node (≥19) and the Electron renderer.

const randomUUID = () => globalThis.crypto.randomUUID();

/**
 * @typedef {'text' | 'stamp' | 'image' | 'redaction' | 'line' | 'rect' | 'signature' | 'page_number'} OverlayType
 */

/**
 * @typedef {object} Overlay
 * @property {string} id
 * @property {number} pageNo
 * @property {OverlayType} type
 * @property {number} x
 * @property {number} y
 * @property {number} w
 * @property {number} h
 * @property {number} zOrder
 * @property {object} properties
 * @property {string | null} assetId
 * @property {string} createdAt   ISO 8601
 * @property {string} updatedAt   ISO 8601
 */

/**
 * @typedef {'add' | 'update' | 'remove' | 'reset'} ChangeKind
 *
 * @typedef {object} ChangeEvent
 * @property {ChangeKind} kind
 * @property {Overlay} [overlay]    add / update / remove
 * @property {number[]} pages       affected pageNos (deduped)
 */

/**
 * @typedef {object} OverlayInput
 * Fields a caller supplies when adding an overlay. id and timestamps are
 * generated by the store.
 *
 * @property {number} pageNo
 * @property {OverlayType} type
 * @property {number} x
 * @property {number} y
 * @property {number} w
 * @property {number} h
 * @property {number} [zOrder]
 * @property {object} [properties]
 * @property {string | null} [assetId]
 */

/**
 * @typedef {object} BBox
 * @property {number} x
 * @property {number} y
 * @property {number} w
 * @property {number} h
 */

/**
 * Set of fields update() may patch. pageNo / type / id are not patchable —
 * change page via remove + add (M3 history will model that as a single op).
 *
 * @typedef {Partial<Pick<Overlay, 'x' | 'y' | 'w' | 'h' | 'zOrder' | 'properties' | 'assetId'>>} OverlayPatch
 */

export class ProjectStore {
  constructor() {
    /** @type {Map<string, Overlay>} */
    this._byId = new Map();
    /** @type {Map<number, Set<string>>} */
    this._byPage = new Map();
    /** @type {Set<(e: ChangeEvent) => void>} */
    this._subscribers = new Set();
    this._dirty = false;
  }

  // ---- queries --------------------------------------------------------

  /** Total overlay count. */
  count() {
    return this._byId.size;
  }

  /** True when any mutation has occurred since construction / reset / markClean. */
  isDirty() {
    return this._dirty;
  }

  /** @param {string} id */
  get(id) {
    return this._byId.get(id) ?? null;
  }

  /**
   * All overlays on a page, sorted by zOrder ascending (createdAt as tie-break).
   * Returns a fresh array each call.
   * @param {number} pageNo
   * @returns {Overlay[]}
   */
  getPageOverlays(pageNo) {
    const ids = this._byPage.get(pageNo);
    if (!ids) return [];
    const out = [];
    for (const id of ids) {
      const ov = this._byId.get(id);
      if (ov) out.push(ov);
    }
    out.sort((a, b) => {
      if (a.zOrder !== b.zOrder) return a.zOrder - b.zOrder;
      return a.createdAt.localeCompare(b.createdAt);
    });
    return out;
  }

  /**
   * Overlays on `pageNo` whose bbox overlaps `rect` (canonical).
   * Linear scan per page; sorted by zOrder for predictable picking order.
   *
   * @param {number} pageNo
   * @param {BBox} rect
   * @returns {Overlay[]}
   */
  hitTest(pageNo, rect) {
    const list = this.getPageOverlays(pageNo);
    const xMax = rect.x + rect.w;
    const yMax = rect.y + rect.h;
    const out = [];
    for (const o of list) {
      if (o.x < xMax && o.x + o.w > rect.x && o.y < yMax && o.y + o.h > rect.y) {
        out.push(o);
      }
    }
    return out;
  }

  // ---- mutations ------------------------------------------------------

  /**
   * Insert a new overlay. id and timestamps are generated.
   * @param {OverlayInput} input
   * @returns {Overlay}
   */
  add(input) {
    const now = new Date().toISOString();
    /** @type {Overlay} */
    const ov = {
      id: randomUUID(),
      pageNo: input.pageNo,
      type: input.type,
      x: input.x,
      y: input.y,
      w: input.w,
      h: input.h,
      zOrder: input.zOrder ?? 0,
      properties: input.properties ?? {},
      assetId: input.assetId ?? null,
      createdAt: now,
      updatedAt: now,
    };
    this._byId.set(ov.id, ov);
    this._addToPageIndex(ov.pageNo, ov.id);
    this._dirty = true;
    this._emit({ kind: "add", overlay: ov, pages: [ov.pageNo] });
    return ov;
  }

  /**
   * Patch fields on an existing overlay. Returns the new snapshot, or null
   * if the id is unknown. updatedAt is bumped automatically.
   *
   * @param {string} id
   * @param {OverlayPatch} patch
   * @returns {Overlay | null}
   */
  update(id, patch) {
    const ov = this._byId.get(id);
    if (!ov) return null;
    /** @type {Overlay} */
    const updated = {
      ...ov,
      ...patch,
      updatedAt: new Date().toISOString(),
    };
    this._byId.set(id, updated);
    this._dirty = true;
    this._emit({ kind: "update", overlay: updated, pages: [updated.pageNo] });
    return updated;
  }

  /**
   * Remove an overlay by id.
   * @param {string} id
   * @returns {boolean} true if removed; false if not found
   */
  remove(id) {
    const ov = this._byId.get(id);
    if (!ov) return false;
    this._byId.delete(id);
    this._removeFromPageIndex(ov.pageNo, id);
    this._dirty = true;
    this._emit({ kind: "remove", overlay: ov, pages: [ov.pageNo] });
    return true;
  }

  /**
   * Replace all overlays atomically. Used by load-from-SQLite (M3).
   * Emits a single 'reset' event with all affected pages.
   * Resets the dirty flag to false (freshly loaded state).
   *
   * @param {Overlay[]} overlays
   */
  reset(overlays) {
    this._byId.clear();
    this._byPage.clear();
    const pages = new Set();
    for (const ov of overlays) {
      this._byId.set(ov.id, ov);
      this._addToPageIndex(ov.pageNo, ov.id);
      pages.add(ov.pageNo);
    }
    this._dirty = false;
    this._emit({ kind: "reset", pages: [...pages] });
  }

  /** Mark store clean (call after a successful save). No event emitted. */
  markClean() {
    this._dirty = false;
  }

  // ---- subscriptions --------------------------------------------------

  /**
   * Subscribe to mutation events. Returns an unsubscribe function.
   * Pass `{ signal }` for AbortController-based cleanup (M3 renderer
   * components attach via the renderer's lifecycle signal).
   *
   * @param {(e: ChangeEvent) => void} callback
   * @param {{ signal?: AbortSignal }} [opts]
   * @returns {() => void} unsubscribe
   */
  subscribe(callback, opts = {}) {
    this._subscribers.add(callback);
    const unsub = () => this._subscribers.delete(callback);
    if (opts.signal) {
      if (opts.signal.aborted) {
        unsub();
      } else {
        opts.signal.addEventListener("abort", unsub, { once: true });
      }
    }
    return unsub;
  }

  // ---- internals ------------------------------------------------------

  /** @param {ChangeEvent} event */
  _emit(event) {
    for (const cb of this._subscribers) {
      try {
        cb(event);
      } catch (err) {
        // Subscribers shouldn't be able to break the store. Surface but continue.
        console.error("[ProjectStore] subscriber threw:", err);
      }
    }
  }

  _addToPageIndex(pageNo, id) {
    let set = this._byPage.get(pageNo);
    if (!set) {
      set = new Set();
      this._byPage.set(pageNo, set);
    }
    set.add(id);
  }

  _removeFromPageIndex(pageNo, id) {
    const set = this._byPage.get(pageNo);
    if (!set) return;
    set.delete(id);
    if (set.size === 0) this._byPage.delete(pageNo);
  }
}
